arxivdigest/frontend/views/admin.py
# -*- coding: utf-8 -*-
__author__ = 'Øyvind Jekteberg and Kristian Gingstad'
__copyright__ = 'Copyright 2020, The arXivDigest project'

from flask import abort
from flask import Blueprint
from flask import g
from flask import jsonify
from flask import render_template

from arxivdigest.core.config import config_email
from arxivdigest.core.config import config_web_address
from arxivdigest.core.mail.mail_server import MailServer
from arxivdigest.frontend.database import admin as db
from arxivdigest.frontend.utils import requiresLogin

mod = Blueprint('admin', __name__)


@mod.before_request
def before_request():
    if not g.loggedIn or not db.isAdmin(g.user):
        return abort(404)
    return None


@mod.route('/', methods=['GET'])
@requiresLogin
def admin():
    """Returns the adminpage"""
    return render_template('admin.html')


@mod.route('/systems/get', methods=['GET'])
@requiresLogin
def getSystems():
    """Returns list of systems from db"""
    return jsonify({'success': True, 'systems': db.getSystems()})


@mod.route('/admins/get', methods=['GET'])
@requiresLogin
def getAdmins():
    """Returns list of admins from db"""
    return jsonify({'success': True, 'admins': db.getAdmins()})


@mod.route('/systems/toggleActive/<int:systemID>/<state>', methods=['PUT'])
@requiresLogin
def toggleSystem(systemID, state):
    """Endpoint for activating and deactivating systems, sets active-value
     for system with <systemID> to <state>"""
    state = True if state.lower() == "true" else False
    if not db.toggleSystem(systemID, state):
        return jsonify(result='Fail')
    if state:
        sys = db.getSystem(systemID)
        mail = {'to_address': sys['email'],
                'subject': 'System Activation',
                'template': 'systemActivation',
                'data': {'name': sys['firstname'] + " " + sys['lastname'],
                         'key': sys['api_key'],
                         'link': config_web_address}}

        Server = MailServer(**config_email)
        try:
            Server.send_mail(**mail)
        except Exception as e:
            return jsonify(result='Success', err='Email error')
        finally:
            Server.close()
    return jsonify(result='Success')


@mod.route('/general', methods=['GET'])
@requiresLogin
def general():
    """This endpoint returns general stats for the project"""
    return jsonify({'success': True,
                    'users': db.getUserStatistics(),
                    'articles': db.getArticleStatistics()
                    })

arxivdigest/frontend/views/articles.py
# -*- coding: utf-8 -*-
__author__ = 'Øyvind Jekteberg and Kristian Gingstad'
__copyright__ = 'Copyright 2020, The arXivDigest project'

import math

from flask import Blueprint
from flask import flash
from flask import g
from flask import jsonify
from flask import redirect
from flask import render_template
from flask import request
from flask import url_for

from arxivdigest.frontend.database import articles as db
from arxivdigest.frontend.utils import pageinate
from arxivdigest.frontend.utils import requiresLogin
from arxivdigest.frontend.database.general import get_user_topics

mod = Blueprint('articles', __name__)

topic_flag = True

def genArticleList(getArticles):
    '''Returns dictionary with: current interval selection, number of articles per page(5), current page, 
    current sort method, pages for pagination div,  number of articles, the articles, values for timedropdown
    and values for sortdropdown. Is a helper function used for showing long list of articles save in index and savedArticles'''
    pageNr = request.args.get('pageNr', 1, type=int)
    if pageNr < 1:
        pageNr = 1
    articlesPerPage = request.args.get('articlesPerPage', 5, type=int)
    if articlesPerPage < 1:
        articlesPerPage = 5
    sortBy = request.args.get('sortBy', 'scoreDesc').lower()
    intervals = {'today': 1, 'thisweek': 7, 'thismonth': 31, 'alltime': 99999}

    def intervalCheck(value):
        if value.lower() not in intervals:
            raise ValueError
        return value
    interval = request.args.get('interval', 'thisWeek', type=intervalCheck)

    intervalDays = intervals.get(interval.lower(), 7)
    start = (pageNr-1)*articlesPerPage
    articles, count = getArticles(g.user, intervalDays, sortBy,
                                  start, articlesPerPage)

    db.seenArticle([(x['article_id'], g.user) for x in articles])

    numberOfPages = math.ceil(count/articlesPerPage)
    pages = pageinate(pageNr, numberOfPages, 15)

    return {'interval': interval.lower(),
            'articlesPerPage': articlesPerPage,
            'currentPage': pageNr,
            'sortBy': sortBy,
            'pages': pages,
            'count': count,
            'articles': articles,
            'timeDropDown': [('today', 'Today'), ('thisweek', 'This week'), ('thismonth', 'This month'), ('alltime', 'All time')],
            'sortDropDown': [('titleasc', 'Title ascending'), ('titledesc', 'Title descending'), ('scoreasc', 'Score ascending'), ('scoredesc', 'Score descending')]
            }


@mod.route('/')
@requiresLogin
def index():
    '''Returns index page with list of articles'''
    if topic_flag:
        return render_template('index.html', endpoint='articles.index', ** genArticleList(db.getUserRecommendations),
                                suggested_topics = get_user_topics(g.user), topic_flag = topic_flag)
    return render_template('index.html', endpoint='articles.index', ** genArticleList(db.getUserRecommendations),
                                topic_flag = topic_flag)


@mod.route('/savedArticles', methods=['GET'])
@requiresLogin
def savedArticles():
    '''Returns savedarticles page with list of saved articles'''
    return render_template('saves.html', endpoint='articles.savedArticles', ** genArticleList(db.getSavedArticles))


@mod.route('/save/<articleID>/<state>', methods=['PUT'])
@requiresLogin
def save(articleID, state):
    '''Endpoint for liking and unliking articles, sets save-value for article with <articleID> to <state>'''
    state = True if state.lower() == "true" else False
    if db.saveArticle(articleID, g.user, state):
        return jsonify(result='Success')
    return jsonify(result='Fail')


@mod.route('/mail/save/<int:userID>/<string:articleID>/<uuid:trace>', methods=['GET'])
def saveEmail(articleID, userID, trace):
    '''Endpoint for liking an article directly from from email. 
    Uses a combination of 3 values to make randomly guessing and bruteforcing almost impossible.'''
    success = db.saveArticleEmail(articleID, userID, str(trace))
    if not success:
        return "Some error occurred."
    if g.loggedIn:
        flash("Saved article %s" % articleID, "success")
        return redirect(url_for("articles.index"))
    flash("Saved article %s" % articleID, "success")
    return redirect(url_for("general.loginPage"))


@mod.route('/mail/read/<int:userID>/<string:articleID>/<uuid:trace>', methods=['GET'])
def readEmail(articleID, userID, trace):
    '''Records clicks from email'''
    db.clickedArticleEmail(articleID, userID, str(trace))
    return redirect('https://arxiv.org/abs/%s' % articleID)


@mod.route('/click/<string:articleId>', methods=['GET'])
@requiresLogin
def click(articleId):
    '''Records if user clicks an article, redirects user to arXiv infopage for article or the article pdf depending on whether <pdf> is true or false'''
    db.clickArticle(articleId, g.user)
    pdf = request.args.get('pdf', False, type=lambda x: x.lower() == 'true')
    if pdf:
        return redirect('https://arxiv.org/pdf/%s.pdf' % articleId)
    return redirect('https://arxiv.org/abs/'+articleId)

arxivdigest/frontend/views/general.py
# -*- coding: utf-8 -*-

__author__ = "Øyvind Jekteberg and Kristian Gingstad"
__copyright__ = "Copyright 2020, The arXivDigest project"

from flask import (
    Blueprint,
    flash,
    g,
    json,
    jsonify,
    make_response,
    redirect,
    render_template,
    request,
    url_for,
)

from arxivdigest.core.config import CONSTANTS
from arxivdigest.frontend.database import general as db
from arxivdigest.frontend.database import general as general_db
from arxivdigest.frontend.database.articles import (
    article_is_recommended_for_user,
    get_article_feedback,
)
from arxivdigest.frontend.forms.feedback_form import (
    ArticleFeedbackForm,
    FeedbackForm,
)
from arxivdigest.frontend.models.errors import ValidationError
from arxivdigest.frontend.models.user import User
from arxivdigest.frontend.models.validate import validPassword
from arxivdigest.frontend.utils import (
    create_gzip_response,
    encode_auth_token,
    requiresLogin,
    send_confirmation_email,
)

mod = Blueprint("general", __name__)


@mod.route("/login", methods=["POST"])
def login():
    """Logs in user based on username and password from form. Returns proper error message on template if
    anything is wrong. Else returns index page and authToken"""
    if g.loggedIn:
        flash("You can't login while you're already logged in.", "danger")
        return redirect(url_for("articles.index"))
    data = request.form

    user = db.validatePassword(data.get("email"), data.get("password"))
    if user is None:
        flash("User doesn't exist.", "danger")
        return render_template("login.html")
    if user is False:
        flash("Invalid password.", "danger")
        return render_template(
            "login.html",
        )
    next = request.args.get("next", "")
    if next != "":
        return make_auth_token_response(user, data.get("email"), next)
    return make_auth_token_response(
        user, data.get("email"), url_for("articles.index")
    )


@mod.route("/login", methods=["GET"])
def loginPage():
    """Returns login page or index page if already logged in"""
    if g.loggedIn:
        if g.inactive:
            return redirect(url_for("general.confirm_email_page"))
        else:
            return redirect(url_for("articles.index"))
    next = request.args.get("next")
    if next:
        err = "You must be logged in to access this endpoint"
        flash(err, "danger")
        return render_template("login.html", next=next)
    return render_template("login.html")


@mod.route("/logout", methods=["GET"])
def logout():
    """Returns login page and sets cookie expire time to 0, so that the user gets logged out"""
    resp = make_response(redirect(url_for("general.loginPage")))
    resp.set_cookie("auth", "", expires=0)
    g.user = None
    g.loggedIn = False
    return resp


@mod.route("/signup", methods=["POST"])
def signup():
    """Takes data from signup form and creates an userobject. Sends user object to signup database function. Returns
    signup page with relevant error or confirm email page and authToken"""
    if g.loggedIn:
        flash("You can not sign up while you are already logged in.", "danger")
        return redirect(url_for("articles.index"))
    user_dict = request.form.to_dict()
    try:
        user = User(user_dict)
    except ValidationError as e:
        flash(e.message, "danger")
        return render_template(
            "signup.html",
            user=user_dict,
            signup=True,
            categoryList=db.getCategoryNames(),
        )
    if db.userExist(user.email):
        flash("Email already used by another account.", "danger")
        return render_template(
            "signup.html",
            user=user_dict,
            signup=True,
            categoryList=db.getCategoryNames(),
        )

    id = db.insertUser(user)

    send_confirmation_email(user.email)
    return make_auth_token_response(
        id, user.email, url_for("general.confirm_email_page")
    )


@mod.route("/signup", methods=["GET"])
def signupPage():
    """Returns signup page or index page if already logged in"""
    if g.loggedIn:
        return redirect(url_for("articles.index"))
    return render_template(
        "signup.html", signup=True, categoryList=db.getCategoryNames()
    )


@mod.route("/passwordChange", methods=["POST"])
@requiresLogin
def passwordChange():
    """Gets old and new password from form. Returns password change template with relevant error
    or profile page on success"""
    data = request.form
    if not data["password"] == data["confirmPassword"]:
        flash("Passwords must match.", "danger")
        return render_template("password_change.html")
    if not validPassword(data["password"]):
        flash("New password is invalid", "danger")
        return render_template("password_change.html")
    if not db.validatePassword(g.email, data["oldPassword"]):
        flash("Old password is wrong.", "danger")
        return render_template("password_change.html")
    db.updatePassword(g.user, data["password"])
    return redirect(url_for("general.profile"))


@mod.route("/passwordChange", methods=["GET"])
@requiresLogin
def passwordChangePage():
    """Returns password change template"""
    return render_template("password_change.html")


@mod.route("/modify", methods=["POST"])
@requiresLogin
def modify():
    """Gets new user data from form. creates user object and sends old user data and new user data to database update
    user function. Returns user modify template with relevant error or user profile template.
    """
    user_dict = request.form.to_dict()
    try:
        user = User(user_dict, require_password=False)
    except ValidationError as e:
        flash(e.message, "danger")
        return render_template(
            "modify.html", user=user_dict, categoryList=db.getCategoryNames()
        )
    if db.userExist(user.email):
        flash("Email already used by another account.", "danger")
        return render_template(
            "modify.html", user=user_dict, categoryList=db.getCategoryNames()
        )

    db.update_user(g.user, user)
    return redirect(url_for("general.profile"))


@mod.route("/topics/search/<search_string>", methods=["GET"])
def topic_search(search_string):
    """Returns a json containing topics starting with ´search_string´."""
    return jsonify(db.search_topics(search_string))


@mod.route("/modify", methods=["GET"])
@requiresLogin
def modifyPage():
    """Returns user modification template with user data filled out"""
    return render_template(
        "modify.html",
        user=db.get_user(g.user),
        categoryList=db.getCategoryNames(),
    )


@mod.route("/profile", methods=["GET"])
@requiresLogin
def profile():
    """Returns user profile page with user info"""
    return render_template("profile.html", user=db.get_user(g.user))


@mod.route("/livinglab/register", methods=["POST"])
@requiresLogin
def registerSystem():
    """Registers a system or returns an error if something went wrong."""
    form = request.form.to_dict()
    if len(form["name"]) > CONSTANTS.max_system_name_length:
        flash(
            "System name must be under {} characters.".format(
                CONSTANTS.max_system_name_length
            ),
            "danger",
        )
        return render_template("register_system.html")
    err, key = db.insertSystem(form["name"], g.user)
    if err:
        flash(err, "danger")
        return render_template("register_system.html")
    flash("Successfully regstered the system with key: " + key, "success")
    return redirect(url_for("general.livinglab"))


@mod.route("/livinglab/register", methods=["GET"])
@requiresLogin
def registerSystemPage():
    """Returns page for registering a new system"""
    return render_template("register_system.html")


@mod.route("/livinglab", methods=["GET"])
@requiresLogin
def livinglab():
    """Returns page for livinglabs with systems belonging to a user"""
    return render_template(
        "living_lab.html",
        systems=db.get_user_systems(g.user),
        user=db.get_user(g.user),
    )


@mod.route("/feedback/", methods=["GET", "POST"])
def feedback():
    """Endpoint for general feedback."""
    form = FeedbackForm()
    if form.validate_on_submit():
        err = db.insertFeedback(
            g.user, None, form.feedback_type.data, form.feedback_text.data, {}
        )
        if err:
            flash(err, "danger")
            return render_template("feedback.html", form=form)

        flash("Successfully sent feedback.", "success")
        return redirect("/")

    return render_template("feedback.html", form=form)


@mod.route("/feedback/articles/<article_id>", methods=["GET", "POST"])
@requiresLogin
def article_feedback(article_id):
    """Submits the feedback form."""
    form = ArticleFeedbackForm()
    if not article_is_recommended_for_user(article_id):
        flash(
            "You can only leave feedback on articles recommended to you.",
            "danger",
        )
        return redirect("/")

    if form.validate_on_submit():
        feedback_vals = {}
        if form.relevance.data is not None:
            feedback_vals["relevance"] = form.relevance.data
        if form.expl_satisfaction.data is not None:
            feedback_vals["expl_satisfaction"] = form.expl_satisfaction.data
        if form.expl_persuasiveness.data is not None:
            feedback_vals["expl_persuasiveness"] = form.expl_persuasiveness.data
        if form.expl_transparency.data is not None:
            feedback_vals["expl_transparency"] = form.expl_transparency.data
        if form.expl_scrutability.data is not None:
            feedback_vals["expl_scrutability"] = form.expl_scrutability.data

        err = db.insertFeedback(
            g.user,
            article_id,
            form.feedback_type.data,
            form.feedback_text.data,
            feedback_vals,
        )
        if err:
            flash(err, "danger")

arxivdigest/frontend/templates/articlelist.html
<div style="min-width: 520px; float:left; margin-bottom:10px;">
    <div class="btn-group" class="sortDiv" style="margin-left:20px;">
        <button type="button" id="leftSort" class="btn btn-secondary sortbutton">
            Showing articles from{% for v in timeDropDown %} {% if interval==v[0] %} {{ v[1].lower() }}
        {% endif %} {% endfor %}
        </button>

        <button type="button" id="rightSort" class="btn btn-secondary dropdown-toggle sortbutton"
                data-toggle="dropdown">
            <span class="caret"></span>
            <span class="sr-only">Toggle Dropdown</span>
        </button>

        <ul class="dropdown-menu" id="dropdownList">
            <h6 class="dropdown-header">Select sorting method</h6>
            {% for v in timeDropDown %}
                <li>
                    <a href="{{ url_for(endpoint,articlesPerPage=articlesPerPage ,sortBy=sortBy,interval=v[0]) }}"
                       {% if interval==v[0] %}class="dropdownActive"
                       {% endif %}>{{ v[1] }}</a>
                </li>
            {% endfor %}
        </ul>
    </div>
    <div class="btn-group" class="sortDiv">
        <button type="button" id="leftSort" class="btn btn-secondary sortbutton">
            Sorted by{% for v in sortDropDown %} {% if sortBy==v[0] %} {{ v[1].lower() }} {% endif %} {% endfor %}
        </button>

        <button type="button" id="rightSort" class="btn btn-secondary dropdown-toggle sortbutton"
                data-toggle="dropdown">
            <span class="caret"></span>
            <span class="sr-only">Toggle Dropdown</span>
        </button>

        <ul class="dropdown-menu" id="dropdownList">
            <h6 class="dropdown-header">Select sorting method</h6>
            {% for v in sortDropDown %}
                <li>
                    <a href="{{ url_for(endpoint,articlesPerPage=articlesPerPage, sortBy=v[0],interval=interval ) }}"
                       {% if sortBy==v[0] %}class="dropdownActive"
                       {% endif %}>{{ v[1] }}</a>
                </li>
            {% endfor %}
        </ul>
    </div>
</div>

{% if articles %} {% for article in articles %}
    <div class="articleDiv">
        <div class="articleInfo">
            <a href="{{ url_for('articles.click', articleId=article.article_id) }}" target="_blank">
                <h4 class="tex2jax_process">{{ article.title }}</h4>
            </a>
            <p class="articleAuthors">{{ article.authors }}</p>
            <p class="articleDescription tex2jax_process">{{ article.abstract }}</p>
            <span>
                <span style="max-width: 75%;"><p class='explanation'>{{ article.explanation | md_bold }}</p></span>
            </span>
            <br>
        </div>
        <div class="articleIcons">
            {% if article.saved %}
                <img src="../static/icons/icon_remove.png" data-value="{{ article.article_id }}" class="saveButton Saved" title="Remove this article from library">
            {% else %}
                <img src="../static/icons/icon_save.png" data-value="{{ article.article_id }}" class="saveButton" title="Add this article to library">
            {% endif %}
            <a href="{{ url_for('articles.click', articleId=article.article_id,pdf=True) }}" target="_blank">
                <img src="../static/icons/icon_pdf.png" class="linkButton" title="Article PDF">
            </a>
            <a href="{{ url_for('general.article_feedback',article_id=article.article_id) }}">
                <img src="../static/icons/icon_feedback.png" class="feedbackButton" title="Give feedback on this recommendation">
            </a>
        </div>
    </div>
{% endfor %} {% else %}
    <div style="clear:both;">
        <hr>
        <h4 style="text-align:center; color:rgb(148, 148, 148);">There are no recommendations for you in the selected period</h4>
    </div>
{% endif %}
<br>
<div id="paginationDiv">
    <nav id="paginationNav" aria-label="Page navigation example">
        <ul class="pagination">

            {% if currentPage == 1 %}
                <li class="page-item disabled">
                    <a class="page-link" tabindex="-1">Previous</a>
                </li>
            {% else %}
                <li class="page-item">
                    <a class="page-link"
                       href="{{ url_for(endpoint,articlesPerPage=articlesPerPage, pageNr=currentPage-1,sortBy=sortBy,interval=interval ) }}">Previous</a>
                </li>
            {% endif %} {% for page in pages %} {% if currentPage==page %}
            <li class="page-item disabled">
                <a class="page-link" tabindex="-1" style="background-color:lightblue;">{{ page }}</a>
            </li>
        {% elif page==-1 %}
            <li class="page-item disabled">
                <a class="page-link" tabindex="-1">...</a>
            </li>
        {% else %}
            <li class="page-item">
                <a class="page-link"
                   href="{{ url_for(endpoint,articlesPerPage=articlesPerPage, pageNr=page,sortBy=sortBy,interval=interval ) }}">{{ page }}</a>
            </li>
        {% endif %} {% endfor %} {% if currentPage==((count/5)|round(0, 'ceil')|int) %}
            <li class="page-item disabled">
                <a class="page-link" tabindex="-1">Next</a>
            </li>
        {% else %}
            <li class="page-item">
                <a class="page-link" href="
                        {{ url_for(endpoint,articlesPerPage=articlesPerPage, pageNr=currentPage+1,sortBy=sortBy,interval=interval ) }}">Next</a>
            </li>
        {% endif %}
        </ul>
    </nav>
</div>

arxivdigest/frontend/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>arXivDigest</title>

    <link rel="stylesheet " href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css ">
    {% assets "css_base" %}
        <link rel="stylesheet" href="{{ ASSET_URL }}">
    {% endassets %}
</head>

<body class="tex2jax_ignore">
<header class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false"
                    aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand inactiveLink" href="#">ar<span class="red">X</span>ivDigest</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                {% if g.loggedIn %}
                    <li class="active">
                        <a href="{{ url_for('general.loginPage') }}" id="homeButton">Recommendations</a>
                    </li>
                    <li>
                        <a href="{{ url_for('articles.savedArticles') }}">Library</a>
                    </li>
                    <li>
                        <a href="{{ url_for('general.profile') }}">Profile</a>
                    </li>
                    {% if g.admin %}
                        <li>
                            <a href="{{ url_for('admin.admin') }}">Admin</a>
                        </li>
                    {% endif %} {% endif %}
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if g.loggedIn %}
                    <li>
                        <a href="#profile" class="inactiveLink"> Logged in as {{ g.email }}</a>
                    </li>
                    <li>
                        <a href="{{ url_for('general.logout') }}" id="logoutButton">Log out</a>
                    </li>
                {% else %}
                    <li>
                        <a href="{{ url_for('general.login') }}" id="loginButton">Login</a>
                    </li>
                    <li>
                        <a href="{{ url_for('general.signup') }}">Signup</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</header> {% with messages = get_flashed_messages(with_categories=true) %} {% if messages %}
    {% for category, message in messages %}
        <div class="alert alert-{{ category }}">
            {{ message }}
        </div>
    {% endfor %} {% endif %} {% endwith %}

{% if semantic_scholar_suggestions %}
    <div class="modal fade" id="semantic-scholar-popup" tabindex="-1" role="dialog" aria-labelledby="semantic-scholar-popup-title">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="semantic-scholar-popup-title">
                        Semantic Scholar profile
                    </h4>
                </div>
                <div class="modal-body">
                    <p>
                        The information available through your Semantic Scholar profile could help to improve the quality of your
                        arXivDigest recommendations. Your profile currently does not contain a link to a Semantic Scholar profile &mdash;
                        would you like to add one now?
                    </p>
                    <p>
                        We have found a few potential candidates for you to choose from:
                    </p>
                    <form id="update-semantic-scholar-form" action="{{ url_for('general.update_semantic_scholar') }}" method="POST" enctype=multipart/form-data>
                        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                        {% for suggestion in semantic_scholar_suggestions %}
                            <div class="checkbox">
                                <label>
                                    <input type="radio" name="s2Id" value="{{ suggestion['semantic_scholar_id'] }}">
                                    <a href="https://semanticscholar.org/author/{{ suggestion['semantic_scholar_id'] }}" target="_blank">
                                        {{ suggestion['name'] }}
                                    </a>
                                </label>
                            </div>
                        {% endfor %}
                        <div class="checkbox">
                            <label>
                                <input type="radio" name="s2Id" value="none">
                                None of the above
                            </label>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-default" data-dismiss="modal" id="close-semantic-scholar-popup">Close</button>
                    <input class="btn btn-primary" form="update-semantic-scholar-form" type="submit" value="Save">
                </div>
            </div>
        </div>
    </div>
{% endif %}

{% block content %} {% endblock %}

<footer>
    <div class="container">
        <div class="alignleft">
            <a href="{{ url_for('general.about') }}" class="footer_item">About</a>
            <span class="footer_item">|</span>
            <a href="{{ url_for('general.terms_and_conditions') }}" class="footer_item">Terms and Conditions</a>
            <span class="footer_item">|</span>
            <a href="{{ url_for('general.privacy_policy') }}" class="footer_item">Privacy Policy</a>
            <span class="footer_item">|</span>
            <a href="{{ url_for('general.livinglab') }}" class="footer_item">Living Lab</a>
            <span class="footer_item">|</span>
            <a href="{{ url_for('general.feedback') }}" class="footer_item">Leave us feedback</a>
        </div>
        <div class="alignright">
            <span class="footer_item">Copyright (c) <a href="http://iai.group/">IAI group</a>, <a href="https://www.uis.no/frontpage/#Studies">University of Stavanger</a></span>
        </div>
    </div>
</footer>
<script>
    MathJax = {
        tex: {
            inlineMath: [['$', '$'], ['\\(', '\\)']]
        },
        svg: {
            fontCache: 'global'
        },
        options: {
            skipHtmlTags: [//  HTML tags that won't be searched for math
                'script', 'noscript', 'style', 'textarea', 'pre',
                'code', 'annotation', 'annotation-xml'
            ],
            includeHtmlTags: {//  HTML tags that can appear within math
                br: '\n', wbr: '', '#comment': ''
            },
            ignoreHtmlClass: 'tex2jax_ignore',    //  class that marks tags not to search
            processHtmlClass: 'tex2jax_process',  //  class that marks tags that should be searched
        }

    };
</script>
<script type="text/javascript" id="MathJax-script" async
        src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js">
</script>
<!-- Libraries - Placed at the end of the page so it loads faster-->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js "></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js "></script>
<script src='https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js'></script>
<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
{% assets "js_base" %}
    <script type="text/javascript" src="{{ ASSET_URL }}"></script>
{% endassets %}

<script type="text/javascript">
    var csrf_token = "{{ csrf_token() }}";

    $.ajaxSetup({
        beforeSend: function (xhr, settings) {
            if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", csrf_token);
            }
        }
    });
</script>

</body>

</html>